### PR TITLE
Login signup fixes

### LINKED ISSUE #3: Add login button to the signup view and signup button to the login view
Currently, a user is forced to sign up and create a new account to get to the login page. There should be a button to get the user to the login page directly and vice versa.

### LINKED ISSUE #6: Better input validation for signing up and logging in
Currently the input validation for signing up is broken in that an empty string is not accepted but a string containing spaces is accepted (though stored as an empty string in the database). Further, there is no way to input an empty string when logging in.

Similar fixes need to be made elsewhere throughout the signup and logging use cases for handling the inputs.

Further, the string passed to the database should be the exact same as the one entered; incorrect inputs should be rejected instead of being modified without the user being informed.

### LINKED ISSUE #13: Add input fields for city and field of expertise to signup page
Add input fields for city and field of expertise to signup page

### PR DESCRIPTION
**Pull request by Pranjal-R-Agrawal**
1. Resolved #3
2. Resolved #6
3. Resolved #13
4. Added isolated interactor tests
5. Added JavaDoc

### CODE REVIEW

File: src/test/java/use_case/signup/SignupInteractorTest.java [hunk 1]
```diff
@@ -0,0 +1,226 @@
...
+        };
+        signupInteractor = new SignupInteractor(mongoDBDataAccessObject, signupPresenter);
+        SignupInputData signupInputData = new SignupInputData("username", "password", "password", "name", "email", "phone", "city", "field");
+        signupInteractor.execute(signupInputData);
+    }
+
+    @Before
+    public void setUpTest() {
+        try {
+            mongoDBDataAccessObject = new MongoDBDataAccessObjectBuilder().setTestParameters().build();
```
Comment (SidharthSawhney) [inline src/test/java/use_case/signup/SignupInteractorTest.java:219]: Just like the Login Interactor test modification that is required, we need to do the same thing here as well.

File: src/test/java/use_case/display_post/DisplayPostInteractorTest.java [hunk 2]
```diff
@@ -0,0 +1,178 @@
...
+            }
+        };
+        DisplayPostInteractor displayPostInteractor = new DisplayPostInteractor(mongoDBDataAccessObject, displayPostOutputBoundary);
+        displayPostInteractor.execute(new DisplayPostInputData(commentID, 0));
+    }
+
+    @Before
+    public void setUpTest() {
+        try {
+            mongoDBDataAccessObject = new MongoDBDataAccessObjectBuilder().setTestParameters().build();
```
Comment (SidharthSawhney) [inline src/test/java/use_case/display_post/DisplayPostInteractorTest.java:171]: Same recommendation in LoginInteractor applies here too.

File: src/test/java/use_case/login/LoginInteractorTest.java [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+        };
+        loginInteractor = new LoginInteractor(mongoDBDataAccessObject, loginOutputBoundary);
+        loginInteractor.execute(new LoginInputData("invalid", "credentials"));
+    }
+
+    @Test
+    public void testValidCredentials() {
+        LoginOutputBoundary loginOutputBoundary = new LoginOutputBoundary() {
+            @Override
+            public void prepareFailView(String error) {fail();}
```
Comment (SidharthSawhney) [inline src/test/java/use_case/login/LoginInteractorTest.java:86]: A message in fail() would be a nice addition and everywhere where fail() is used-maybe state the reason of failure

File: src/main/java/use_case/signup/interface_adapter/SignupPresenter.java [hunk 4]
```diff
@@ -31,9 +41,23 @@ public void prepareSuccessView(SignupOutputData user) {
         viewManagerModel.firePropertyChanged();
```
Comment (SidharthSawhney) [inline src/main/java/use_case/signup/interface_adapter/SignupPresenter.java:41]: this code could be replaced by having  goToLogin() invoked here

File: src/test/java/use_case/signup/SignupInteractorTest.java [hunk 5]
```diff
@@ -0,0 +1,226 @@
...
+            public void prepareSuccessView(SignupOutputData user) {fail();}
+            @Override
+            public void prepareFailView(String error) {
+                assertEquals(error, "Username already used.");
+            }
+            @Override
+            public void goToLogin() {fail();}
+        };
+        signupInteractor = new SignupInteractor(mongoDBDataAccessObject, signupPresenter);
+        mongoDBDataAccessObject.addUser(new User("username", "password", "name", "email", "phone", "city", "field"));
```
Comment (SidharthSawhney) [inline src/test/java/use_case/signup/SignupInteractorTest.java:196]: User factory should be used to create user preferably, to abide with the Single Responsibility Principle

File: src/main/java/app/DisplayPostUseCaseFactory.java [hunk 6]
```diff
@@ -11,6 +11,13 @@
 public class DisplayPostUseCaseFactory {
```
Comment (SidharthSawhney) [inline src/main/java/app/DisplayPostUseCaseFactory.java:11]: Factory Design pattern well implemented

File: src/main/java/view/SignupView.java [hunk 7]
```diff
@@ -19,8 +19,11 @@ public class SignupView extends JPanel implements PropertyChangeListener {
     private final JTextField nameInputField = new JTextField(20);
     private final JTextField phoneNumberInputField = new JTextField(20);
     private final JTextField emailInputField = new JTextField(20);
+    private final JTextField cityInputField = new JTextField(20);
+    private final JTextField fieldOfExpertiseInputField = new JTextField(20);
     private final SignupController signupController;
     private final JButton signupButton = new JButton();
+    private final JButton loginButton = new JButton();
 
     public SignupView(SignupViewModel signupViewModel, SignupController signupController) {
```
Comment (SidharthSawhney) [inline src/main/java/view/SignupView.java:28]: Add Javadoc

**Review by SidharthSawhney — CHANGES_REQUESTED** [review]
JavaDoc for all public classes and public constructors and methods are required, there are some place that hasn't been included. Clean Architecture is being followed well as the dependencies are pointing inwards. Please check the inline reviews for specific changes that are required. Well done!

File: src/test/java/use_case/login/LoginInteractorTest.java (hunk 3 above)
Comment (Pranjal-R-Agrawal) [reply src/test/java/use_case/login/LoginInteractorTest.java:87]: There isn't any particular reason, just that the the input is valid so the interactor shouldn't fail.

**Comment by Pranjal-R-Agrawal** [comment]
@SidharthSawhney I have made the requested changes.

File: src/test/java/use_case/display_post/DisplayPostInteractorTest.java [hunk 8]
```diff
@@ -0,0 +1,173 @@
...
+import use_case.display_post.application_business_rules.DisplayPostInteractor;
+import use_case.display_post.application_business_rules.DisplayPostOutputBoundary;
+import use_case.display_post.application_business_rules.DisplayPostOutputData;
+import data_access.MongoDBDataAccessObject;
+import data_access.MongoDBDataAccessObjectBuilder;
+
+import java.util.ArrayList;
+import java.util.Arrays;
+public class DisplayPostInteractorTest {
+    MockSignupLoginDisplayPostDataAccessObject mongoDBDataAccessObject;
```
Comment (SidharthSawhney) [inline src/test/java/use_case/display_post/DisplayPostInteractorTest.java:21]: you will  have to change the file variable names as it could get confusing in all the interactor tests

File: src/main/java/view/SignupView.java [hunk 9]
```diff
@@ -19,16 +19,26 @@ public class SignupView extends JPanel implements PropertyChangeListener {
     private final JTextField nameInputField = new JTextField(20);
     private final JTextField phoneNumberInputField = new JTextField(20);
     private final JTextField emailInputField = new JTextField(20);
+    private final JTextField cityInputField = new JTextField(20);
+    private final JTextField fieldOfExpertiseInputField = new JTextField(20);
     private final SignupController signupController;
     private final JButton signupButton = new JButton();
+    private final JButton loginButton = new JButton();
 
+    /**
```
Comment (SidharthSawhney) [inline src/main/java/view/SignupView.java:28]: The SignupView class on line 13 will also need javadoc

**Review by SidharthSawhney — CHANGES_REQUESTED** [review]
Interactor tests are well implemented! Integration tests are now required to be done where we use the real MongoDB database instead of the mock, take a look at the current main, ull see how each use case has an integration test and interactor. Ur previous code for the tests with the real DB was correct but I said back then to keep those and rename them to integration tests instead of interactor tests. This will help with line coverage, moreover tests for interactor integration and interactor with mock DB is a requirement for us! Overall, well done!

**Comment by Pranjal-R-Agrawal** [comment]
> Integration tests are now required to be done where we use the real MongoDB database instead of the mock

Aren't integration tests beyond the scope for the project? I believe the DAO tests (implemented in another branch, merged into main by now), combined with the isolated interactor tests should be enough.

**Review by SidharthSawhney — APPROVED** [review]

**Review by YathusanK — APPROVED** [review]
Fixes to code function well and JavaDoc was added to public methods. Your interactor and integration tests also are written well!
